---
- name: Install Xen
  apt:
    name: xen-system-{{ xen_arch }}
  register: install

- name: Write GRUB configuration and boot selection override
  template:
    src: xen.cfg.j2
    dest: /etc/default/grub.d/xen.cfg
  register: grubcfg

- name: Update GRUB
  command: update-grub
  when: install.changed or grubcfg.changed

- name: Reboot
  shell: sleep 2; systemctl reboot
  # Don't wait for completion
  async: 1
  poll: 0
  ignore_errors: true
  when: install.changed

- name: Wait for server to come back
  become: no
  wait_for_connection:
    delay: "{{ xen_reboot_delay }}"
    timeout: "{{ xen_reboot_timeout }}"
  when: install.changed
